'use client'
import { Heebo } from 'next/font/google'
import { Provider } from 'react-redux'
import './globals.css'
import { store } from './store/store'

const inter = Heebo({ subsets: ['latin'], weight: ['500', '200', '300', '400', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <div>{children}</div>
        </Provider>
        <div id="modal"></div>
      </body>
    </html>
  )
}
